### ISSUE TITLE
Generating Report Dashboard

### ISSUE THREAD

**Issue by GriggsRice** [QAInsights/PerfAction#19]
After running the Jmeter test, I would like to generate html dashboard report, this would usually be done with `jmeter -g results.jtl -o results dashboard.html` is there a way to add this to the action.yml that will work?

**Comment by amardeep2006** [comment]
@GriggsRice You show be able to do it via arguments.

```
- name: JMeter Test
  uses: QAInsights/PerfAction@v3.1
  with:
    test-plan-path: ./TestPlans/S01_SimpleExample/S01_SimpleExample.jmx
    args: "-e -o ./reports/html/"
    
- name: Upload Results
  uses: actions/upload-artifact@v3
  with:
    name: jmeter-results
    path: result.jtl

- name: Upload HTML Reports
  uses: actions/upload-artifact@v3
  with:
    name: jmeter-html-reports
    path: reports
```
