### ISSUE TITLE
How to install a JMeter plugin to be used in the action?

### ISSUE THREAD

**Issue by yyahav** [QAInsights/PerfAction#37]
In the action description it says:

> `test-plan-path`
> - Mandatory
> - JMeter test plan and its dependencies such as test data, plugins etc

But how do I add the plugin dependency?
```
- name: Run JMeter Tests
        uses: QAInsights/PerfAction@v5.6.2
        with:
          test-plan-path: load_test.jmx
          args: "-Jduration=3600 -Jusers=250"
          results-file: logs/result.jtl
```

I get this error when running:
```
Error in NonGUIDriver java.lang.IllegalArgumentException: Problem loading XML from:'/github/workspace/load_test.jmx'. 
Cause:
CannotResolveClassException: eu.luminis.jmeter.wssampler.RequestResponseWebSocketSampler

 Detail:com.thoughtworks.xstream.converters.ConversionException: 
---- Debugging information ----
cause-exception     : com.thoughtworks.xstream.converters.ConversionException
cause-message       : 
first-jmeter-class  : org.apache.jmeter.save.converters.HashTreeConverter.unmarshal(HashTreeConverter.java:66)
class               : org.apache.jmeter.save.ScriptWrapper
required-type       : org.apache.jmeter.save.ScriptWrapper
converter-type      : org.apache.jmeter.save.ScriptWrapperConverter
path                : /jmeterTestPlan/hashTree/hashTree/hashTree[[14](#step:5:15)]/hashTree[7]/eu.luminis.jmeter.wssampler.RequestResponseWebSocketSampler
line number         : 9769
version             : 5.6.2
-------------------------------
```
